#!/bin/bash

LIBDIR="/usr/local/lib/qgm-unc-prune"
EXECCONF="/tmp/$$_uncprune.js"

DRYRUN=true
DAYS=14

echo "-------------------------------------------"
if [ -f /etc/qgm-unc-prune.conf ]; then
echo "Reading config /etc/qgm-unc-prune.conf "
. /etc/qgm-unc-prune.conf
fi

echo "Pruning DB entrys older than $DAYS days"
if [ $DRYRUN == "true" ]; then 
    echo "Running in dryrun mode. Not modifying DB"
fi
echo "-------------------------------------------"

if [ ! -f ${LIBDIR}/prune_unc.js ]; then 
    echo "Prune script not found in ${LIBDIR}/prune_unc.js"
    echo "Exiting."
    exit 1
else
    sed "s/^var days=.*$/var days=${DAYS};/" ${LIBDIR}/prune_unc.js > $EXECCONF
    sed -i "s/^var dryrun=.*$/var dryrun=${DRYRUN};/" $EXECCONF
    mongo --port 27117 < $EXECCONF
    rm $EXECCONF
fi




